import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/Providers/ThemeProvider";
import Navbar from "@/components/navbar/Navbar";
import ReactQueryProvider from "@/Providers/ReactQueryProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            disableTransitionOnChange
            defaultTheme="system"
            enableSystem
          >
            <Navbar>{children}</Navbar>
            <Toaster richColors position="bottom-right" theme="dark" />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
