import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Providers/ThemeProvider";
import Navbar from "@/components/navbar/Navbar";
import ReactQueryProvider from "@/Providers/ReactQueryProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            disableTransitionOnChange
            defaultTheme="system"
            enableSystem
          >
            <div className="relative w-full h-full">
              <Navbar />
              {children}
            </div>
            <Toaster richColors position="bottom-right" theme="dark" />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
