export const LOGIN = "/api/auth/signin";

export const currencies = [
  { country: "United States", symbol: "$" },
  { country: "European Union", symbol: "€" },
  { country: "United Kingdom", symbol: "£" },
  { country: "Japan", symbol: "¥" },
  { country: "Australia", symbol: "$" },
  { country: "Canada", symbol: "$" },
  { country: "Switzerland", symbol: "Fr" },
  { country: "India", symbol: "₹" },
  { country: "Russia", symbol: "₽" },
  { country: "South Africa", symbol: "R" },
  { country: "Mexico", symbol: "$" },
  { country: "Brazil", symbol: "R$" },
  { country: "Turkey", symbol: "₺" },
  { country: "China", symbol: "¥" },
  { country: "Hong Kong", symbol: "$" },
  { country: "Singapore", symbol: "$" },
  { country: "New Zealand", symbol: "$" },
  { country: "United Arab Emirates", symbol: "د.إ" },
  { country: "Saudi Arabia", symbol: "﷼" },
  { country: "South Korea", symbol: "₩" },
  { country: "Indonesia", symbol: "Rp" },
  { country: "Malaysia", symbol: "RM" },
  { country: "Philippines", symbol: "₱" },
  { country: "Thailand", symbol: "฿" },
  { country: "Pakistan", symbol: "₨" },
  { country: "Bangladesh", symbol: "৳" },
  { country: "Israel", symbol: "₪" },
  { country: "Egypt", symbol: "ج.م" },
  { country: "Morocco", symbol: "د.م" },
  { country: "Kenya", symbol: "Sh" },
  { country: "Nigeria", symbol: "₦" },
  { country: "Jamaica", symbol: "$" },
  { country: "Colombia", symbol: "$" },
  { country: "Venezuela", symbol: "Bs" },
  { country: "Chile", symbol: "$" },
  { country: "Peru", symbol: "S/" },
  { country: "Uruguay", symbol: "$" },
  { country: "Argentina", symbol: "$" },
];
